version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 80:80
            - 81:81
            - 443:443
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: proyecto2024
            MYSQL_DATABASE: dbempresa
            MYSQL_USER: proyecto
            MYSQL_PASSWORD: proyecto
        ports:
            - 3306:3306

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8001:80
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
  
   
